// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIjYKGkxpc3RFbWJlZGRpbmdNb2RlbHNSZXF1ZXN0EhgKC3Byb3ZpZGVyX2lkGAEgASgJQgPgQQIiSwobTGlzdEVtYmVkZGluZ01vZGVsc1Jlc3BvbnNlEiwKBm1vZGVscxgBIAMoCzIcLm1lbW9zLmFwaS52MS5FbWJlZGRpbmdNb2RlbCIrCg5FbWJlZGRpbmdNb2RlbBIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCTKcAQoJQUlTZXJ2aWNlEo4BChNMaXN0RW1iZWRkaW5nTW9kZWxzEigubWVtb3MuYXBpLnYxLkxpc3RFbWJlZGRpbmdNb2RlbHNSZXF1ZXN0GikubWVtb3MuYXBpLnYxLkxpc3RFbWJlZGRpbmdNb2RlbHNSZXNwb25zZSIigtPkkwIcEhovYXBpL3YxL2FpL2VtYmVkZGluZ01vZGVsc0KmAQoQY29tLm1lbW9zLmFwaS52MUIOQWlTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.ListEmbeddingModelsRequest
 */
export type ListEmbeddingModelsRequest = Message<"memos.api.v1.ListEmbeddingModelsRequest"> & {
  /**
   * Required. The id of a configured AI provider.
   *
   * @generated from field: string provider_id = 1;
   */
  providerId: string;
};

/**
 * Describes the message memos.api.v1.ListEmbeddingModelsRequest.
 * Use `create(ListEmbeddingModelsRequestSchema)` to create a new message.
 */
export const ListEmbeddingModelsRequestSchema: GenMessage<ListEmbeddingModelsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.ListEmbeddingModelsResponse
 */
export type ListEmbeddingModelsResponse = Message<"memos.api.v1.ListEmbeddingModelsResponse"> & {
  /**
   * @generated from field: repeated memos.api.v1.EmbeddingModel models = 1;
   */
  models: EmbeddingModel[];
};

/**
 * Describes the message memos.api.v1.ListEmbeddingModelsResponse.
 * Use `create(ListEmbeddingModelsResponseSchema)` to create a new message.
 */
export const ListEmbeddingModelsResponseSchema: GenMessage<ListEmbeddingModelsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.EmbeddingModel
 */
export type EmbeddingModel = Message<"memos.api.v1.EmbeddingModel"> & {
  /**
   * id is the provider model identifier sent with embedding requests.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * title is a display name. It may match id when the provider has no separate title.
   *
   * @generated from field: string title = 2;
   */
  title: string;
};

/**
 * Describes the message memos.api.v1.EmbeddingModel.
 * Use `create(EmbeddingModelSchema)` to create a new message.
 */
export const EmbeddingModelSchema: GenMessage<EmbeddingModel> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * ListEmbeddingModels returns embedding models advertised by one configured provider.
   *
   * @generated from rpc memos.api.v1.AIService.ListEmbeddingModels
   */
  listEmbeddingModels: {
    methodKind: "unary";
    input: typeof ListEmbeddingModelsRequestSchema;
    output: typeof ListEmbeddingModelsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

