// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIkkKEVRyYW5zY3JpYmVSZXF1ZXN0EjQKBWF1ZGlvGAEgASgLMiAubWVtb3MuYXBpLnYxLlRyYW5zY3JpcHRpb25BdWRpb0ID4EECIncKElRyYW5zY3JpcHRpb25BdWRpbxIWCgdjb250ZW50GAEgASgMQgPgQQRIABINCgN1cmkYAiABKAlIABIVCghmaWxlbmFtZRgDIAEoCUID4EEBEhkKDGNvbnRlbnRfdHlwZRgEIAEoCUID4EEBQggKBnNvdXJjZSIiChJUcmFuc2NyaWJlUmVzcG9uc2USDAoEdGV4dBgBIAEoCSI2ChpMaXN0RW1iZWRkaW5nTW9kZWxzUmVxdWVzdBIYCgtwcm92aWRlcl9pZBgBIAEoCUID4EECIksKG0xpc3RFbWJlZGRpbmdNb2RlbHNSZXNwb25zZRIsCgZtb2RlbHMYASADKAsyHC5tZW1vcy5hcGkudjEuRW1iZWRkaW5nTW9kZWwiKwoORW1iZWRkaW5nTW9kZWwSCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkylwIKCUFJU2VydmljZRJ5CgpUcmFuc2NyaWJlEh8ubWVtb3MuYXBpLnYxLlRyYW5zY3JpYmVSZXF1ZXN0GiAubWVtb3MuYXBpLnYxLlRyYW5zY3JpYmVSZXNwb25zZSIo2kEFYXVkaW+C0+STAho6ASoiFS9hcGkvdjEvYWk6dHJhbnNjcmliZRKOAQoTTGlzdEVtYmVkZGluZ01vZGVscxIoLm1lbW9zLmFwaS52MS5MaXN0RW1iZWRkaW5nTW9kZWxzUmVxdWVzdBopLm1lbW9zLmFwaS52MS5MaXN0RW1iZWRkaW5nTW9kZWxzUmVzcG9uc2UiIoLT5JMCHBIaL2FwaS92MS9haS9lbWJlZGRpbmdNb2RlbHNCpgEKEGNvbS5tZW1vcy5hcGkudjFCDkFpU2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vdXNlbWVtb3MvbWVtb3MvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.TranscribeRequest
 */
export type TranscribeRequest = Message<"memos.api.v1.TranscribeRequest"> & {
  /**
   * Required. Audio input.
   *
   * @generated from field: memos.api.v1.TranscriptionAudio audio = 1;
   */
  audio?: TranscriptionAudio | undefined;
};

/**
 * Describes the message memos.api.v1.TranscribeRequest.
 * Use `create(TranscribeRequestSchema)` to create a new message.
 */
export const TranscribeRequestSchema: GenMessage<TranscribeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.TranscriptionAudio
 */
export type TranscriptionAudio = Message<"memos.api.v1.TranscriptionAudio"> & {
  /**
   * @generated from oneof memos.api.v1.TranscriptionAudio.source
   */
  source: {
    /**
     * Inline audio bytes.
     *
     * @generated from field: bytes content = 1;
     */
    value: Uint8Array;
    case: "content";
  } | {
    /**
     * URI for audio content. Reserved for future use.
     *
     * @generated from field: string uri = 2;
     */
    value: string;
    case: "uri";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. The uploaded filename.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Optional. The MIME type of the input audio.
   *
   * @generated from field: string content_type = 4;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.TranscriptionAudio.
 * Use `create(TranscriptionAudioSchema)` to create a new message.
 */
export const TranscriptionAudioSchema: GenMessage<TranscriptionAudio> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.TranscribeResponse
 */
export type TranscribeResponse = Message<"memos.api.v1.TranscribeResponse"> & {
  /**
   * The transcribed text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.TranscribeResponse.
 * Use `create(TranscribeResponseSchema)` to create a new message.
 */
export const TranscribeResponseSchema: GenMessage<TranscribeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from message memos.api.v1.ListEmbeddingModelsRequest
 */
export type ListEmbeddingModelsRequest = Message<"memos.api.v1.ListEmbeddingModelsRequest"> & {
  /**
   * Required. The id of a configured AI provider.
   *
   * @generated from field: string provider_id = 1;
   */
  providerId: string;
};

/**
 * Describes the message memos.api.v1.ListEmbeddingModelsRequest.
 * Use `create(ListEmbeddingModelsRequestSchema)` to create a new message.
 */
export const ListEmbeddingModelsRequestSchema: GenMessage<ListEmbeddingModelsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 3);

/**
 * @generated from message memos.api.v1.ListEmbeddingModelsResponse
 */
export type ListEmbeddingModelsResponse = Message<"memos.api.v1.ListEmbeddingModelsResponse"> & {
  /**
   * @generated from field: repeated memos.api.v1.EmbeddingModel models = 1;
   */
  models: EmbeddingModel[];
};

/**
 * Describes the message memos.api.v1.ListEmbeddingModelsResponse.
 * Use `create(ListEmbeddingModelsResponseSchema)` to create a new message.
 */
export const ListEmbeddingModelsResponseSchema: GenMessage<ListEmbeddingModelsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4);

/**
 * @generated from message memos.api.v1.EmbeddingModel
 */
export type EmbeddingModel = Message<"memos.api.v1.EmbeddingModel"> & {
  /**
   * id is the provider model identifier sent with embedding requests.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * title is a display name. It may match id when the provider has no separate title.
   *
   * @generated from field: string title = 2;
   */
  title: string;
};

/**
 * Describes the message memos.api.v1.EmbeddingModel.
 * Use `create(EmbeddingModelSchema)` to create a new message.
 */
export const EmbeddingModelSchema: GenMessage<EmbeddingModel> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 5);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * Transcribe transcribes an audio file using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Transcribe
   */
  transcribe: {
    methodKind: "unary";
    input: typeof TranscribeRequestSchema;
    output: typeof TranscribeResponseSchema;
  },
  /**
   * ListEmbeddingModels returns embedding models advertised by one configured provider.
   *
   * @generated from rpc memos.api.v1.AIService.ListEmbeddingModels
   */
  listEmbeddingModels: {
    methodKind: "unary";
    input: typeof ListEmbeddingModelsRequestSchema;
    output: typeof ListEmbeddingModelsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

